[project]
name = "market-data-platform"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "kungpaugasol", email = "kungpaugasol@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "dbt-core>=1.12.4",
    "dbt-postgres>=1.11.0",
    "logging>=0.4.9.6",
    "pandas>=3.0.5",
    "pandera>=0.33.1",
    "pathlib>=1.0.1",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.3",
    "tenacity>=9.1.4",
    "uuid>=1.30",
    "yfinance>=1.7.0",
]

[project.scripts]
market-data-platform = "market_data_platform:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
